name: Pre-release Terraform Plan
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-plan:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: docker
        run: |
          IMAGE_TAG=backend-pr-${{ github.event.pull_request.number }}
          cd backend_image && docker build -t $IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::877680973630:role/Terraform_ECS_Backent
          aws-region: eu-central-1


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform refresh
        id: refresh
        run: terraform refresh
        continue-on-error: true


      - name: Terraform Plan 
        id: plan
        run:  terraform plan  -no-color -var="docker_image=${{ steps.docker.outputs.image_tag }}" > release-plan.txt
        continue-on-error: true

      - name: Upload Terraform Plan
        id: upload
        if: steps.refresh.outcome == 'success' && steps.plan.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: release-plan.txt


      - name: Create GitHub Pre-release
        if: steps.upload.outcome == 'success' 
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-realase-${{ github.run_number }}
          name: Pre-release for commit ${{ github.sha  }}
          body: |
            Pre-release with Terraform plan for Backend.
          prerelease: true
          files: release-plan.txt
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      - name: Send plan to Telegram (as file)
        if: steps.refresh.outcome == 'success' && steps.plan.outcome == 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: release-plan.txt
          message: "✅ Terraform plan was successful for Closed PR and Create Pre-release in Backend."


      - name: Send Telegram message
        if: steps.refresh.outcome != 'success' || steps.plan.outcome != 'success' || steps.upload.outcome != 'success'
        uses: appleboy/telegram-action@master
        with: 
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ Terraform plan failed for Closed PR in Backend. Please check the GitHub Actions logs."
          
